
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("cb67b145-22ad-4e16-93dc-9c7cd5fc4fa9")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("InheritedModel", "PrimaryDataSecondaryData", "PrimaryData", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(TPTPrimaryData), "SecondaryData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(TPTSecondaryData), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class InheritedModelContainer
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new InheritedModelContainer object using the connection string found in the 'InheritedModelContainer' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=InheritedModelContainer", "InheritedModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new InheritedModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "InheritedModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new InheritedModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "InheritedModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property TPTDataItems() As ObjectSet(Of TPTDataItem)
        Get
            If (_TPTDataItems Is Nothing) Then
                _TPTDataItems = MyBase.CreateObjectSet(Of TPTDataItem)("TPTDataItems")
            End If
            Return _TPTDataItems
        End Get
    End Property

    Private _TPTDataItems As ObjectSet(Of TPTDataItem)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the TPTDataItems EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTPTDataItems(ByVal tPTDataItem As TPTDataItem)
        MyBase.AddObject("TPTDataItems", tPTDataItem)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="InheritedModel", Name:="TPTDataItem")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
<KnownTypeAttribute(GetType(TPTPrimaryData))>
<KnownTypeAttribute(GetType(TPTSecondaryData))>
Public Partial Class TPTDataItem
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TPTDataItem object.
    ''' </summary>
    ''' <param name="index">Initial value of the Index property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="value">Initial value of the Value property.</param>
    Public Shared Function CreateTPTDataItem(index As Global.System.Int32, name As Global.System.String, value As Global.System.String) As TPTDataItem
        Dim tPTDataItem as TPTDataItem = New TPTDataItem
        tPTDataItem.Index = index
        tPTDataItem.Name = name
        tPTDataItem.Value = value
        Return tPTDataItem
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Index() As Global.System.Int32
        Get
            Return _Index
        End Get
        Set
            If (_Index <> Value) Then
                OnIndexChanging(value)
                ReportPropertyChanging("Index")
                _Index = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Index")
                OnIndexChanged()
            End If
        End Set
    End Property

    Private _Index As Global.System.Int32
    Private Partial Sub OnIndexChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIndexChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Value() As Global.System.String
        Get
            Return _Value
        End Get
        Set
            OnValueChanging(value)
            ReportPropertyChanging("Value")
            _Value = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Value")
            OnValueChanged()
        End Set
    End Property

    Private _Value As Global.System.String
    Private Partial Sub OnValueChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnValueChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="InheritedModel", Name:="TPTPrimaryData")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TPTPrimaryData
    Inherits TPTDataItem
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TPTPrimaryData object.
    ''' </summary>
    ''' <param name="index">Initial value of the Index property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="value">Initial value of the Value property.</param>
    ''' <param name="identifier">Initial value of the Identifier property.</param>
    Public Shared Function CreateTPTPrimaryData(index As Global.System.Int32, name As Global.System.String, value As Global.System.String, identifier As Global.System.String) As TPTPrimaryData
        Dim tPTPrimaryData as TPTPrimaryData = New TPTPrimaryData
        tPTPrimaryData.Index = index
        tPTPrimaryData.Name = name
        tPTPrimaryData.Value = value
        tPTPrimaryData.Identifier = identifier
        Return tPTPrimaryData
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Identifier() As Global.System.String
        Get
            Return _Identifier
        End Get
        Set
            OnIdentifierChanging(value)
            ReportPropertyChanging("Identifier")
            _Identifier = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Identifier")
            OnIdentifierChanged()
        End Set
    End Property

    Private _Identifier As Global.System.String
    Private Partial Sub OnIdentifierChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdentifierChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("InheritedModel", "PrimaryDataSecondaryData", "SecondaryData")>
     Public Property SecondaryDatas() As EntityCollection(Of TPTSecondaryData)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of TPTSecondaryData)("InheritedModel.PrimaryDataSecondaryData", "SecondaryData")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of TPTSecondaryData)("InheritedModel.PrimaryDataSecondaryData", "SecondaryData", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="InheritedModel", Name:="TPTSecondaryData")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TPTSecondaryData
    Inherits TPTDataItem
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TPTSecondaryData object.
    ''' </summary>
    ''' <param name="index">Initial value of the Index property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="value">Initial value of the Value property.</param>
    ''' <param name="identifier">Initial value of the Identifier property.</param>
    ''' <param name="primaryDataIndex">Initial value of the PrimaryDataIndex property.</param>
    Public Shared Function CreateTPTSecondaryData(index As Global.System.Int32, name As Global.System.String, value As Global.System.String, identifier As Global.System.String, primaryDataIndex As Global.System.Int32) As TPTSecondaryData
        Dim tPTSecondaryData as TPTSecondaryData = New TPTSecondaryData
        tPTSecondaryData.Index = index
        tPTSecondaryData.Name = name
        tPTSecondaryData.Value = value
        tPTSecondaryData.Identifier = identifier
        tPTSecondaryData.PrimaryDataIndex = primaryDataIndex
        Return tPTSecondaryData
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Identifier() As Global.System.String
        Get
            Return _Identifier
        End Get
        Set
            OnIdentifierChanging(value)
            ReportPropertyChanging("Identifier")
            _Identifier = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Identifier")
            OnIdentifierChanged()
        End Set
    End Property

    Private _Identifier As Global.System.String
    Private Partial Sub OnIdentifierChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIdentifierChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PrimaryDataIndex() As Global.System.Int32
        Get
            Return _PrimaryDataIndex
        End Get
        Set
            OnPrimaryDataIndexChanging(value)
            ReportPropertyChanging("PrimaryDataIndex")
            _PrimaryDataIndex = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PrimaryDataIndex")
            OnPrimaryDataIndexChanged()
        End Set
    End Property

    Private _PrimaryDataIndex As Global.System.Int32
    Private Partial Sub OnPrimaryDataIndexChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPrimaryDataIndexChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("InheritedModel", "PrimaryDataSecondaryData", "PrimaryData")>
    Public Property PrimaryData() As TPTPrimaryData
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TPTPrimaryData)("InheritedModel.PrimaryDataSecondaryData", "PrimaryData").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TPTPrimaryData)("InheritedModel.PrimaryDataSecondaryData", "PrimaryData").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PrimaryDataReference() As EntityReference(Of TPTPrimaryData)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TPTPrimaryData)("InheritedModel.PrimaryDataSecondaryData", "PrimaryData")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of TPTPrimaryData)("InheritedModel.PrimaryDataSecondaryData", "PrimaryData", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

