ALTER TABLE [dbo].[Leaves]
    ADD CONSTRAINT [PK_Leaves] PRIMARY KEY CLUSTERED ([Index] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

